version: 0.2

env:
  variables:
    CLOUD_BUILD: "True"
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - sudo yum install gdal-bin
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py test --keepdb
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - ./*


