version: 0.2

env:
  variables:
    CLOUD_BUILD: "True"
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - wget https://github.com/OSGeo/gdal/releases/download/v3.2.0/gdal-3.2.0.tar.gz && tar -xvf gdal-3.2.0.tar.gz
      - cd gdal-3.2.0 && ./configure --with-proj=/usr/local --with-python && sudo make && sudo make install
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py test --keepdb
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - ./*


