version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pylint --load-plugins pylint_django traffic_finder_server api
      - python manage.py test
  post_build:
    commands:
      - echo Build passed on `date`


