# Generated by Django 3.1.2 on 2020-11-11 21:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_dir', models.CharField(blank=True, max_length=50, null=True)),
                ('link_id', models.IntegerField(blank=True, null=True)),
                ('st_name', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(blank=True, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('link_dir', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tx', models.DateTimeField()),
                ('length', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('stddev', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('pct_50', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travel_time',
                'managed': False,
            },
        ),
    ]
