# Generated by Django 3.1.2 on 2020-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201115_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('link_dir', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tx', models.DateTimeField()),
                ('length', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('stddev', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('pct_50', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travel_time',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HereData',
        ),
    ]
